version: '0.1'
guardians:
  - chain: substrate
    nodeEndpoint:
      - wss://kusama-rpc.polkadot.io/
    monitors:
      - task: system.events
        id: transfer_event # optional
        arguments:
          name:
            - balances.Transfer
        actions:
          - method: script
            path: ./save_to_csv.py
