version: '0.1'
guardians:
  ethereum:
    networkType: ethereum
    network: kovan
    nodeEndpoint: wss://kovan.infura.io/ws/v3/16a5aa3a08c24d56b1586cd06b4055d5
    monitors:
      syntheticPoolGeneral-FEUR:
        task: synthetic.pools
        arguments:
          poolId: '0x61A7645ef693Ea7740b121232Ddc7b874Be7Fa09'
          tokenName: 'FEUR'
        actions:
          - method: ethereumLiquidate
            maxCollateralRatio: 1.02
